apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-news-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-news-api
  template:
    metadata:
      labels:
        app: fake-news-api
    spec:
      containers:
      - name: fake-news-container
        image: lucasrbnc/fake-news-api:latest
        ports:
        - containerPort: 8000
