apiVersion: v1
kind: Service
metadata:
  name: fake-news-service
spec:
  type: NodePort
  selector:
    app: fake-news-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007
